### ISSUE TITLE
Split analysis and report

### ISSUE THREAD

**Issue by JanAlexanderPersonal** [JanAlexanderPersonal/PrinstatProject#3]
Volgens de opdracht moeten we 2 aparte files opleveren:

1. Report in PDF
2. R-document met analyse

De R-Markdown file zoals ik nog begon moet dus worden gesplitst.

**Comment by JanAlexanderPersonal** [comment]
Overstappen naar LaTex als we toch splitsen?

**Comment by pmorbee** [comment]
Ik denk dat dit toch aangewezen is. Zelf ken ik wel geen Latex, ik kan het leren maar in het kader van dit werk denk ik niet dat dit de meest gunstige werkverdeling zou zijn.
